export const listEthnics = [

  { "name": "Kinh" },
  { "name": "Tày" },
  { "name": "Thái" },
  { "name": "Hoa" },
  { "name": "Khơ-me" },
  { "name": "Mường" },
  { "name": "Nùng" },
  { "name": "HMông" },
  { "name": "Dao" },
  { "name": "Gia-rai" },
  { "name": "Ngái" },
  { "name": "Ê-đê" },
  { "name": "Ba na" },
  { "name": "Xơ-Đăng" },
  { "name": "Sán Chay" },
  { "name": "Cơ-ho" },
  { "name": "Chăm" },
  { "name": "Sán Dìu" },
  { "name": "Hrê" },
  { "name": "Mnông" },
  { "name": "Ra-glai" },
  { "name": "Xtiêng" },
  { "name": "Bru-Vân Kiều" },
  { "name": "Thổ" },
  { "name": "Giáy" },
  { "name": "Cơ-tu" },
  { "name": "Gié Triêng" },
  { "name": "Mạ" },
  { "name": "Khơ-mú" },
  { "name": "Co" },
  { "name": "Tà-ôi" },
  { "name": "Chơ-ro" },
  { "name": "Kháng" },
  { "name": "Xinh-mun" },
  { "name": "Hà Nhì" },
  { "name": "Chu ru" },
  { "name": "Lào" },
  { "name": "La Chí" },
  { "name": "La Ha" },
  { "name": "Phù Lá" },
  { "name": "La Hủ" },
  { "name": "Lự" },
  { "name": "Lô Lô" },
  { "name": "Chứt" },
  { "name": "Mảng" },
  { "name": "Pà Thẻn" },
  { "name": "Co Lao" },
  { "name": "Cống" },
  { "name": "Bố Y" },
  { "name": "Si La" },
  { "name": "Pu Péo" },
  { "name": "Brâu" },
  { "name": "Ơ Đu" }
]


export const formattedEthnics = [
  { value: "", label: "Chọn dân tộc" },
  { value: "Kinh", label: "Kinh" },
  { value: "Tày", label: "Tày" },
  { value: "Thái", label: "Thái" },
  { value: "Hoa", label: "Hoa" },
  { value: "Khơ-me", label: "Khơ-me" },
  { value: "Mường", label: "Mường" },
  { value: "Nùng", label: "Nùng" },
  { value: "HMông", label: "HMông" },
  { value: "Dao", label: "Dao" },
  { value: "Gia-rai", label: "Gia-rai" },
  { value: "Ngái", label: "Ngái" },
  { value: "Ê-đê", label: "Ê-đê" },
  { value: "Ba na", label: "Ba na" },
  { value: "Xơ-Đăng", label: "Xơ-Đăng" },
  { value: "Sán Chay", label: "Sán Chay" },
  { value: "Cơ-ho", label: "Cơ-ho" },
  { value: "Chăm", label: "Chăm" },
  { value: "Sán Dìu", label: "Sán Dìu" },
  { value: "Hrê", label: "Hrê" },
  { value: "Mnông", label: "Mnông" },
  { value: "Ra-glai", label: "Ra-glai" },
  { value: "Xtiêng", label: "Xtiêng" },
  { value: "Bru-Vân Kiều", label: "Bru-Vân Kiều" },
  { value: "Thổ", label: "Thổ" },
  { value: "Giáy", label: "Giáy" },
  { value: "Cơ-tu", label: "Cơ-tu" },
  { value: "Gié Triêng", label: "Gié Triêng" },
  { value: "Mạ", label: "Mạ" },
  { value: "Khơ-mú", label: "Khơ-mú" },
  { value: "Co", label: "Co" },
  { value: "Tà-ôi", label: "Tà-ôi" },
  { value: "Chơ-ro", label: "Chơ-ro" },
  { value: "Kháng", label: "Kháng" },
  { value: "Xinh-mun", label: "Xinh-mun" },
  { value: "Hà Nhì", label: "Hà Nhì" },
  { value: "Chu ru", label: "Chu ru" },
  { value: "Lào", label: "Lào" },
  { value: "La Chí", label: "La Chí" },
  { value: "La Ha", label: "La Ha" },
  { value: "Phù Lá", label: "Phù Lá" },
  { value: "La Hủ", label: "La Hủ" },
  { value: "Lự", label: "Lự" },
  { value: "Lô Lô", label: "Lô Lô" },
  { value: "Chứt", label: "Chứt" },
  { value: "Mảng", label: "Mảng" },
  { value: "Pà Thẻn", label: "Pà Thẻn" },
  { value: "Co Lao", label: "Co Lao" },
  { value: "Cống", label: "Cống" },
  { value: "Bố Y", label: "Bố Y" },
  { value: "Si La", label: "Si La" },
  { value: "Pu Péo", label: "Pu Péo" },
  { value: "Brâu", label: "Brâu" },
  { value: "Ơ Đu", label: "Ơ Đu" }
];
